version: 2
references:
  ## Workspaces
  workspace: &workspace
               ~/src

  ## Docker image configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-28
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

  ## Dependencies
  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: bundle check || bundle install --path vendor/bundle

  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

jobs:

  ## Analyzing code
  analyzer:
    <<: *android_config
    steps:
    - checkout
    - run:
        name: Generating Gradle wrapper files âš™ï¸...
        command: ./gradlew wrapper
    - run:
        name: Cleaning ðŸ§¹...
        command: ./gradlew clean
    - run:
        name: Building project ðŸ—...
        command: ./gradlew build
    - run:
        name: Checking against possible bugs ðŸ‘€...
        command: ./gradlew check && ./gradlew assemble

  ## Run unit tests
  unit-tests:
    <<: *android_config
    steps:
    - checkout
    - run:
        name: Running unit tests ðŸ¥¶...
        command: ./gradlew test

  ## Deploy to slack goodsmart channel
  deploy_slack:
    <<: *android_config
    steps:
    - checkout
    - *ruby_dependencies
    - *android_dependencies
    - run:
        name: Deploy to slack goodsmart channel
        command: bundle exec fastlane build_debug_apk

workflows:
  version: 2
  ci_workflow:
    jobs:
    - analyzer
    - unit-tests
    - deploy_slack:
        filters:
          branches:
            only:
              - master
        requires:
          - analyzer
          - unit-tests
